"""add a map table

Revision ID: 24ce32bec1b9
Revises: a2df1676dc81
Create Date: 2022-05-05 08:33:51.769449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ce32bec1b9'
down_revision = 'a2df1676dc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('html', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.name'], ),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map')
    # ### end Alembic commands ###
