"""initial migration

Revision ID: a2df1676dc81
Revises: 
Create Date: 2022-05-05 08:33:08.949058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2df1676dc81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('count',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.name'], ),
    sa.PrimaryKeyConstraint('date', 'username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    op.drop_table('user')
    # ### end Alembic commands ###
