"""add width and height

Revision ID: c408e8e6930b
Revises: 24ce32bec1b9
Create Date: 2022-05-05 08:34:16.932960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c408e8e6930b'
down_revision = '24ce32bec1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
